on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CREDS_RG_SALT_LAKE_AZURE_GROUP }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: 'rg-salt-lake-user-group'
        template: ./.iac/logicapp.bicep
        parameters: location=westus2 
                    logicAppName=la-slag-demo
                    appServicePlanName=asp-la-slag-demo
                    storageName=stlaslagdemo
        failOnStdErr: false



 
 
