name: Azure ARM

on: 
    workflow_dispatch:
        inputs:
          logicAppName:
            description: 'Logic App Name'     
            required: true
            default: 'la-default'
          appServicePlanName:
            description: 'App Service Name'     
            required: true
            default: 'asp-la-default'
          storageAccountName:
            description: 'Storage Account Name'     
            required: true
            default: 'stlaendpoint'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1      
      with:
        creds: ${{ secrets.Azure_Creds }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCEGROUP }}
        template: ./.iac/logicapp.bicep
        parameters: location=westus 
                    logicAppName=${{github.event.inputs.logicAppName}}
                    appServicePlanName=${{github.event.inputs.appServicePlanName}}
                    storageName=${{github.event.inputs.storageAccountName}}
        failOnStdErr: false



 
 
