name: Azure ARM

on: workflow_dispatch 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1      
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }} 
          
        #creds: ${{ secrets.Azure_Creds }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: 'openhackqj13fpm0rg'
        template: ./.iac/logicapp.bicep
        parameters: location=westus2 
                    logicAppName=la-endpoint
                    appServicePlanName=asp-la-endpoint
                    storageName=stlaendpoint
        failOnStdErr: false



 
 
